[package]
name = "dojo-discord-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.11.5"
tokio = { version = "1.25.0", features = ["rt-multi-thread", "macros"] }
rand = "0.8.5"
